### ISSUE TITLE
errors always log

### ISSUE THREAD

**Issue by OmgImAlexis** [SaltyAom/kingworld#15]
```ts
import { KingWorld } from 'kingworld';

new KingWorld()
    .get('/', () => 'Hi')
    .get('/error', () => {
        throw new Error('test')
    })
    .onError(error => {
        console.log(error.name === 'test');
    })
    .listen(8080)
```

If you start the app and visit `http://localhost:8080/error` should only see "false" in the logs, instead I see this.

```
➜  bun-test git:(main) ✗ bun run ./src/index.ts
[0.09ms] ".env"
false
1 | import { KingWorld } from 'kingworld';
2 | 
3 | new KingWorld()
4 |     .get('/', () => 'Hi')
5 |     .get('/error', () => {
6 |         throw new Error('test')
                  ^
error: test
      at /Users/xo/code/bun-test/src/index.ts:6:14
      at /Users/xo/code/bun-test/node_modules/kingworld/build/es/index.js:285:24
      at handle (/Users/xo/code/bun-test/node_modules/kingworld/build/es/index.js:220:17)
```

**Comment by OmgImAlexis** [comment]
A better example. `/works` prints nothing to the console. `/broken` prints the error.

```ts
import { KingWorld } from 'kingworld';

new KingWorld()
    .onError(error => {
        return new Response(error.message, {
            status: Number(error.code ?? 500),
            statusText: error.message ?? 'Internal Server Error'
        });
    })
    .get('/broken', () => {
        throw new Error('test');
    })
    .get('/works', () => {
        try {
            throw new Error('test');
        } catch (error) {
            return new Response(error.message, {
                status: Number(error.code ?? 500),
                statusText: error.message ?? 'Internal Server Error'
            });
        }
    })
    .listen(8080)
```

**Comment by SaltyAom** [comment]
I understand that the all error log is annoying, tbh I also looking for a way to disable error logging. 

From what I found, if an Error is thrown in the async function in Bun, it will always log an error, the bug is now [reported](https://github.com/oven-sh/bun/issues/1435) and pending on Bun.

Please keep this issue until [1435](https://github.com/oven-sh/bun/issues/1435) is fixed, to see if the issue still occurs.
